In [2]:
import tensorflow as tf

In [3]:
# Intitialization 
# Mathematical operation of tensor 
# Indexing
# Reshaping 


'2.8.0'

In [42]:
from numpy import float32
# Intitialization : 
tf.constant(3,shape=(1,1),dtype=float32) 

# 2 * 2 matrix 
tf.constant(3,shape=(2,4))

tf.constant([[1,2,3],[1,12,2]]) 

tf.zeros((3,3)) # one matrix 
tf.ones((2,2))  # Zero Matrix 

tf.eye(3,3)  # Identity Matrix 
tf.random.normal((3,2),mean=0,stddev=1)   # To check Normal Distribution 
tf.random.uniform((3,3),minval=1,maxval=3) # Uniform Distribution 

# tensor also has there range variable 
for i in tf.range(start=3,limit=10,delta=3):
  print(i)

x = 21.2222
# Convert into any type easily 
tf.cast(x,dtype=tf.int32)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [28]:
# Mathematical Operation
x1 = tf.constant([[1,1,1],[2,3,1]])
x2 = tf.constant([1,2,3])
x3 = tf.add(x1,x2)
print(x1,x2)
print(x3)

x3 = tf.subtract(x1,x2)
print(x3)

x3 = tf.divide(x1,x2)
print(x3)

x3 = tf.multiply(x1,x2)
print(x3)
print("*"*3)
x3 = tf.tensordot(x1,x2,axes=1)
print(x3)
c1=tf.constant([1,1])
c2=tf.constant([2,3])




# product sum
c4 = tf.tensordot(c1,c2,axes=1)
print(c4)   # They will return the same result 
c3 = tf.reduce_sum(c1*c2,axis=0)
print(c3)   
print(c1 ** 3)

# Matrix multiplication
a=tf.random.normal((2,3))
b = tf.random.normal((3,4))
c = tf.matmul(a,b)
print(c)
c = a @ b
print(c)


# Indexing 
x5=tf.range(11)
print(x5[:])

x6=tf.constant([[1,2],[2,4]])
print(x6)

x6[1:]
# ind=(x6[:])
# x_ind = tf.gather(x6,ind)
# print(x_ind)


# RESHAPING 
t1=tf.range(9)
t2=tf.reshape(t1,(3,3))
t3 = tf.transpose(t2)
print(t3)

tf.Tensor(
[[1 1 1]
 [2 3 1]], shape=(2, 3), dtype=int32) tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[2 3 4]
 [3 5 4]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 0 -1 -2]
 [ 1  1 -2]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1.         0.5        0.33333333]
 [2.         1.5        0.33333333]], shape=(2, 3), dtype=float64)
tf.Tensor(
[[1 2 3]
 [2 6 3]], shape=(2, 3), dtype=int32)
***
tf.Tensor([ 6 11], shape=(2,), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor(
[[-3.6399665  -1.4099743   1.5716612   1.0960695 ]
 [ 1.8920189  -0.5182395  -1.2415419  -0.76029646]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-3.6399665  -1.4099743   1.5716612   1.0960695 ]
 [ 1.8920189  -0.5182395  -1.2415419  -0.76029646]], shape=(2, 4), dtype=float32)
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10], shape=(11,), dtype=int32)
tf.Tensor(
[[1 2]
 [2 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]